server:
  port: 8081

spring:
  application:
    name: CRUD app
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/mycrudappdb
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  rabbitmq:
    request-queue:
      name: cud.in.queue.requests
    listener:
      simple:
        default-requeue-rejected: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  endpoint:
    health:
      show-components: always
      show-details: always


